"""Declarative source registry for the Altel CTI bulletin."""

FUENTES = [
    {
        "id": "cisa_kev",
        "nombre": "CISA Known Exploited Vulnerabilities",
        "tipo": "json_kev",
        "url": "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json",
        "idioma": "en",
        "region": "global",
        "peso": 1.0,
        "nota": "Unica fuente que otorga EXPLOTADO ACTIVAMENTE.",
    },
    {
        "id": "microsoft_msrc",
        "nombre": "Microsoft Security Response Center",
        "tipo": "msrc_cvrf_actual",
        "url": "https://api.msrc.microsoft.com/cvrf/v3.0/cvrf",
        "idioma": "en",
        "region": "global",
        "peso": 1.0,
        "nota": "Fuente oficial para Patch Tuesday y advisories de Microsoft.",
    },
    {
        "id": "cisa_advisories",
        "nombre": "CISA Advisories",
        "tipo": "rss",
        "url": "https://www.cisa.gov/cybersecurity-advisories/all.xml",
        "idioma": "en",
        "region": "global",
        "peso": 1.0,
    },
    {
        "id": "cisa_ics",
        "nombre": "CISA ICS Advisories",
        "tipo": "rss",
        "url": "https://www.cisa.gov/cybersecurity-advisories/ics-advisories.xml",
        "idioma": "en",
        "region": "global",
        "peso": 1.0,
    },
    {
        "id": "ecucert",
        "nombre": "EcuCERT Alertas",
        "tipo": "scrape_ecucert",
        "url": "https://www.ecucert.gob.ec/alertas/",
        "idioma": "es",
        "region": "ec",
        "peso": 1.0,
    },
    {
        "id": "csirt_telconet",
        "nombre": "CSIRT Telconet",
        "tipo": "rss",
        "url": "https://csirt.telconet.net/feed/",
        "paginas": 5,
        "idioma": "es",
        "region": "ec",
        "peso": 1.0,
    },
    {
        "id": "ransomware_ec",
        "nombre": "Ransomware.live Ecuador",
        "tipo": "json_ransomware_ec",
        "url": "https://api.ransomware.live/v2/countryvictims/EC",
        "idioma": "en",
        "region": "ec",
        "peso": 1.0,
    },
    {
        "id": "thehackernews",
        "nombre": "The Hacker News",
        "tipo": "rss",
        "url": "https://feeds.feedburner.com/TheHackersNews",
        "idioma": "en",
        "region": "global",
        "peso": 1.0,
    },
    {
        "id": "bleepingcomputer",
        "nombre": "BleepingComputer",
        "tipo": "rss",
        "url": "https://www.bleepingcomputer.com/feed/",
        "idioma": "en",
        "region": "global",
        "peso": 1.0,
    },
    {
        "id": "securityweek",
        "nombre": "SecurityWeek",
        "tipo": "rss",
        "url": "https://www.securityweek.com/feed/",
        "idioma": "en",
        "region": "global",
        "peso": 1.0,
    },
    {
        "id": "segu_info",
        "nombre": "Segu-Info",
        "tipo": "rss",
        "url": "https://blog.segu-info.com.ar/feeds/posts/default",
        "idioma": "es",
        "region": "latam",
        "peso": 1.0,
    },
    {
        "id": "malwarebytes",
        "nombre": "Malwarebytes Labs",
        "tipo": "rss",
        "url": "https://www.malwarebytes.com/blog/feed/index.xml",
        "idioma": "en",
        "region": "global",
        "peso": 1.0,
    },
    {
        "id": "krebs",
        "nombre": "KrebsOnSecurity",
        "tipo": "rss",
        "url": "https://krebsonsecurity.com/feed/",
        "idioma": "en",
        "region": "global",
        "peso": 1.0,
    },
    {
        "id": "trufflesecurity",
        "nombre": "Truffle Security",
        "tipo": "sitemap_diff",
        "url": "https://trufflesecurity.com/sitemap.xml",
        "idioma": "en",
        "region": "global",
        "peso": 0.4,
    },
    {
        "id": "snwire",
        "nombre": "Security News Wire",
        "tipo": "rss",
        "url": "https://www.snwire.com/feed/",
        "idioma": "en",
        "region": "global",
        "peso": 0.4,
    },
]

ENRIQUECIMIENTO = {
    "epss": "https://epss.empiricalsecurity.com/epss_scores-current.csv.gz",
    "poc_github": "https://raw.githubusercontent.com/nomi-sec/PoC-in-GitHub/master/README.md",
}
